name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install buildozer

    - name: Initialize Buildozer
      run: buildozer init  # Ensure buildozer is initialized

    - name: Create bin directory
      run: mkdir -p bin  # Ensure the bin folder exists

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: MyApp-APK
        path: bin/*.apk
