name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      if: success()  # This ensures the artifact is uploaded only if the build is successful
      uses: actions/upload-artifact@v2
      with:
        name: MyApp-APK
        path: bin/*.apk
