name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip zip unzip
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init  # Ensures buildozer.spec exists

    - name: Update buildozer.spec
      run: |
        sed -i 's/# source.dir = ./source.dir = ./' buildozer.spec
        sed -i 's/# version = 1.0.0/version = 1.0.0/' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug || buildozer -v android debug  # Retry if it fails

    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APK
        path: bin/*.apk
